services:
  db_service:
    image: postgres:15
    container_name: db-container
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:


networks:
  default:
    name: shared_net
    external: true
